questions = ["Which Seinfeld character is based on creator Larry David?",
"What was Kramer's original name in the pilot?",
"Who is Seinfeld's favorite D.C. superhero?",
"What is George's self-proclaimed nickname?",
"What is the name of the recurring lawyer character?",
"What prompted Kramer to run off to LA in the Season 3 finale?",
"What was the name of George's late fiance?",
"What was the name of fashion catalog Elaine worked for?",
"What is the higehest rated Seinfeld episode on IMDB?",
"What is Elaine's relationship to Jerry throughout the show?",
"How many seasons did Seinfeld run for?",
"Why was Newman created as a character?",
"What is the show's motto?",
"Which one of these is NOT a nickname for Jerry?",
"What is the name of George's father?",
"Which of these was Larry David's last full season?",
"Which one of these characters has appeared in every episode?",
"What is the name of Jerry's quirky uncle?",
"What is the name of the resturant that appears in almost every Seinfeld Episode?",
"What city does Seinfeld take place in?"]


correct = ["George",
"Kessler",
"Superman",
"King of Idiots",
"Jackie Chiles",
"Keys",
"Susan",
"James Peterman",
"The Contest",
"Ex-girlfriend",
"9",
"To satirize the US Postal System",
"No hugging, no learning",
"Superman",
"Frank",
"Season 7",
"Jerry",
"Uncle Leo",
"Tom's Resturaunt",
"New York"]



options = [[correct[0], "Kramer", "Steinberg", "Newman"],
[correct[1], "Cosmo", "Kevin", "Coney"],
["Batman", "Wonder Woman", correct[2], "Aquaman"],
["King of Bald", correct[3], "The Brains", "The Charmer"],
["Phoenix Wright", "Saul Goodman", "Ken Wesely", correct[4]],
[correct[5], "Food", "Rent", "Drugs"],
["Sarah", "Sally", correct[6], "Sandra"],
["Macy's", correct[7], "Sandra Harrison", "Like a Spring Breeze"],
["The Soup Nazi", "The Marine Biologist", "The Outing", correct[8]],
[correct[9], "Sister-in-Law", "Best Friend", "Neighbor"],
["8", "15", correct[10], "10"],
["To Give Kramer a Best Friend", correct[11], "To Act as Elaine's Love Interest", "To Be a Foil to George"],
[correct[12], "A show about nothing", "The dark cousin of Friends", "That's a shame"],
["Even Steven", "Neat Freak", "Funny Man", correct[13]],
[correct[14], "Fred", "Flint", "Fredrick"],
["Season 9", "Season 3", correct[15], "Season 1"],
["Kramer", correct[16], "George", "Elaine"],
["Uncle Tommy", "Uncle Wally", "Uncle Marty", correct[17]],
[correct[18], "Mimi's Cafe", "Reggie's", "Sandwich Shack"],
["Los Angeles", "Philadelphia", correct[19], "Washington D.C."]
]